
services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ../wordpress_data:/var/www/html
    depends_on:
      - wordpress
    restart: on-failure
    networks:
      - inception

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    volumes:
      - ../wordpress_data:/var/www/html
    env_file:
      - .env
    depends_on:
      - mariadb
    restart: on-failure
    expose:
      - 9000
    networks:
      - inception

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    restart: on-failure
    volumes:
      - ../mariadb_data:/var/lib/mysql
    env_file:
      - .env
    expose:
      - 3306
    networks:
      - inception

networks:
  inception:
    driver: bridge

#change the volumes path to your local path TODO
volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/valeria/Code/inception_test/mariadb_data

  wordpress_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/valeria/Code/inception_test/wordpress_data
