
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    depends_on:
      - wordpress
      - mariadb
    env_file:
      - .env
    networks:
      - backend
    volumes:
      - wordpress_data:/var/www/html:delegated
    restart: always

  mariadb:
    build:
      context: ./mariadb
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - backend
    restart: always

  wordpress:
    container_name: wordpress
    ports:
      - "9000:9000"
    networks:
      - backend
    build:
      context: ./wordpress
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html:delegated
    depends_on:
      - mariadb
    restart: always

networks:
  backend:

volumes:
  mariadb_data:
  wordpress_data: